@?/md/admin/catsem.sql

DROP TABLESPACE rdftbs INCLUDING CONTENTS AND DATAFILES;
CREATE BIGFILE TABLESPACE rdftbs
DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/rdftbs01.dbf' SIZE 1G;

--GRANT INHERIT PRIVILEGES ON USER sys TO mdsys;
CONNECT system/Welcome1@ORCLPDB1
EXECUTE SEM_APIS.CREATE_SEM_NETWORK('rdftbs');

DROP USER rdfuser CASCADE;
CREATE USER rdfuser IDENTIFIED BY Welcome1
DEFAULT TABLESPACE rdftbs TEMPORARY TABLESPACE temp;
GRANT connect, resource, unlimited tablespace TO rdfuser;

EXIT
